sonar.projectKey=aura-music
sonar.projectName=Aura Music
sonar.sources=frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/public/**,**/assets/**
sonar.host.url=http://sonarqube:9000
